apiVersion: v1
kind: PersistentVolume
metadata:
  name: command-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/command-db" # Adjust this path as needed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: command-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
