apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
data:
  POSTGRES_DB: cHJldF9kYg== # Base64 encoded 'pret_db'
  POSTGRES_USER: cG9zdGdyZXM= # Base64 encoded 'postgres'
  POSTGRES_PASSWORD: c2VjcmV0 # Base64 encoded 'secret'
