apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service
  labels:
    app: query-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      labels:
        app: query-service
    spec:
      containers:
        - name: query-service
          image: query-service:latest  # Replace with your image name
          imagePullPolicy: IfNotPresent  
          ports:
            - containerPort: 8082
          env:
            - name: MONGO_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: query-service-configmap  # Replace with your ConfigMap name
                  key: mongo_db_host
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: query-service-configmap  # Replace with your ConfigMap name
                  key: kafka_bootstrap_servers
            - name: JAEGER_AGENT_HOST
              valueFrom:
                configMapKeyRef:
                  name: query-service-configmap  # Replace with your ConfigMap name
                  key: jaeger_agent_host
            - name: JAEGER_AGENT_PORT
              value: "4317"
---
apiVersion: v1
kind: Service
metadata:
  name: query-service
spec:
  type: LoadBalancer  # Change to LoadBalancer or NodePort as needed
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: query-service
